name: CI                                                                                                                                                              

on: [push]

jobs:
  test-lint:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
        - name: Install Go
          uses: actions/setup-go@v1
          with:
            go-version: ${{ matrix.go-version }}
        - name: Checkout Code
          uses: actions/checkout@v1
        - name: Install golangci-lint
          run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.22.2
        - name: Test
          run: go test ./...
        - name: GolangCI-Lint
          run: $(go env GOPATH)/bin/golangci-lint run ./...
